# Generated by Django 3.0.5 on 2020-04-28 17:27

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, null=True, unique=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_got', models.BigIntegerField()),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('imageUrl', models.URLField(max_length=250)),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'ordering': ('id',),
            },
        ),
    ]
